linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 320
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
linters:
  disable-all: true
  enable:
    #    - bodyclose
    - gofmt
    - goimports
    - govet
    #    - ineffassign
    #    - interfacer
    #    - lll
    #    - misspell
    - nakedret
    #    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - structcheck
    #    - stylecheck
    - unconvert
    #    - unparam
    - varcheck
    #   - whitespace
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gosimple
    - linters:
        - revive
      text: "dot-imports:"
run:
service:
  golangci-lint-version: 1.42.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
