#!/bin/bash

if [[ "$1" = "" ]]; then
	echo "Usage: ""$0"" <number>"
	exit 1
fi

if [[ "$TEST_HOST" = "" ]]; then
	TEST_HOST="localhost:8080"
fi

findy-agent create schema \
-sc_name "schema_new_findy"
-sc_version "1.0"
-cloudpw "h""$1" \
-url "http://""$TEST_HOST" \
-wallet "c""$1" \
-pwd "c""$1"
