#!/bin/bash

if [[ "$2" = "" ]]; then
	echo "Usage: ""$0"" <number> <cred_def_id>"
	exit 1
fi

if [[ "$TEST_HOST" = "" ]]; then
	TEST_HOST="localhost:8080"
fi

findy-agent client \
credDef \
-id "$2" \
-cloudpw "h""$1" \
-url "http://""$TEST_HOST" \
-wallet "c""$1" \
-pwd "c""$1"
