#!/bin/bash

go run .. server \
-wallet "sovrin_steward_wallet" \
-pwd "4Vwsj6Qcczmhk2Ak7H5GGvFE1cQCdRtWfW4jchahNUoE" \
-pool "FINDY_MEM_LEDGER" \
-did "Th7MpTaRZVRYnPiabds81Y" \
-register "../findy.json" \
-hostaddr "localhost" \
-logging "-logtostderr=true -v=1"

