#!/bin/bash

if [[ "$1" = "" ]]; then
	echo "Usage: ""$0"" <number>"
	exit 1
fi

if [[ "$TEST_HOST" = "" ]]; then
	TEST_HOST="localhost:8080"
fi

findy-agent client \
ping \
-cloudpw "h""$1" \
-url "http://""$TEST_HOST" \
-wallet "c""$1" \
-pwd "c""$1"
