#!/bin/bash

if [[ "$3" = "" ]]; then
        echo "Usage: ""$0"" <n1> <n2> <2endp-url>"
        exit 1
fi

if [[ "$TEST_HOST" = "" ]]; then
	TEST_HOST="localhost"
fi

if [[ "$TEST_PORT" = "" ]]; then
	TEST_PORT=8080
fi

findy-agent client \
pairwise \
-cloudpw "h""$1" \
-url "http://""$TEST_HOST"":""$TEST_PORT" \
-wallet "c""$1" \
-pwd "c""$1" \
-edgepw "h""$1""$2" \
-endp "$3" \
-hostaddr "$TEST_HOST" \
-port "$TEST_PORT"
