@startuml

node "Service Agent Node" {
	database "ChatDB" {
	}
	[SA]
}

node "Browser Node" {
	database "test" {
	}
	[PWA]
}

node "Vault Node" {
	package "FindyVault.app" {
		database "VaultDB - SQL"  #Lightblue {
		}
		GrapdQL - [QueryProcessor]
		[QueryProcessor] - DataPump
	}
}

node "WebAuthn Server Node" {
	package "FIDO2 Server" {
		FIDO - [Server]
		database "Enclave" {
		}
	}
}

node "Agency Node" {
	database "Cloud Wallet"  #Lightblue {
	}
	database "LMDB" {
		[PSM]
	}
	package "Findy Agent" {
		gRPC - [CA]
		[wEA]
		[CA] --> [wEA]
		[ProtocolProcessor] - AriesIN
		[ProtocolProcessor] -left-> [CA]
		database "wEA Wallet" #Yellow {
			[creds]
		}
'		note bottom of [creds]
'			teste
'		end note
		[wEA] -> [creds]
	}
	[ProtocolProcessor] <--> [PSM]: protocol state
	package "FindyGo" {
		[libindy]
	}
}

node "Ext Agency" #lightgray {
	 Aries - [Agent]
}

[QueryProcessor] <..> gRPC: API calls

AriesIN <.. [Agent]
[ProtocolProcessor] ..> Aries

[PWA] ..> [GrapdQL]
[PWA] ..> [FIDO]

[SA] ..> [FIDO]
[SA] ..> [gRPC]


@enduml
