#!/bin/bash

. ./functions.sh

agency=${agency:-"go run ../.."}
pool=${pool:-"FINDY_MEM_LEDGER,"}
wpool_size=${wsize:-"50"}

enclaveFile=${enclave:-"mem/enclave.bolt"}
register=${register:-"mem/findy.json"}
psm_file=${psm_file:-"mem/findy.bolt"}

if [[ -z ${no_clean} && ! -z ${pool} ]]; then
	echo -n "'no_clean' not defined, going to reset all. "
	if [[ $(prompt_default_no) == "no" ]]; then
		no_clean=yes
	fi
fi
if [[ -z ${no_clean} ]]; then
	echo "Backuping & cleaning..."
	mkdir -p mem/
	mv "$enclaveFile" "$enclaveFile".bak
	mv "$register" "$register".bak
	echo -n "{}" > "$register"
fi

echo $@

read -r -d '' myCmd << EOM
$agency agency start $@ \
--steward-wallet-name sovrin_steward_wallet \
--steward-wallet-key 4Vwsj6Qcczmhk2Ak7H5GGvFE1cQCdRtWfW4jchahNUoE \
--pool-name $pool \
--steward-did Th7MpTaRZVRYnPiabds81Y \
--register-file "$register" \
--register-backup "" \
--register-backup-interval 0h \
--enclave-path $enclaveFile \
--host-address localhost \
--psm-database-file "$psm_file" \
--wallet-pool $wpool_size
EOM

eval $myCmd
