#!/bin/bash

agency=${fcli_agency:-"go run ../.."}
pool=${fcli_pool:-"FINDY_MEM_LEDGER,"}
wpool_size=${fcli_wsize:-"50"}

enclaveFile="mem/enclave.bolt"
register="mem/findy.json"

if [[ -z ${no_clean} ]]; then
	echo "cleaning..."
	mv "$enclaveFile" "$enclaveFile".bak
	echo -n "{}" > "$register"
fi

echo $@

read -r -d '' myCmd << EOM
$agency agency start $@ \
--steward-wallet-name sovrin_steward_wallet \
--steward-wallet-key 4Vwsj6Qcczmhk2Ak7H5GGvFE1cQCdRtWfW4jchahNUoE \
--pool-name $pool \
--steward-did Th7MpTaRZVRYnPiabds81Y \
--register-file "$register" \
--register-backup-interval 300h \
--enclave-path $enclaveFile \
--host-address localhost \
--wallet-pool $wpool_size
EOM

eval $myCmd
